# Generated by Django 2.2 on 2020-02-06 13:35

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='leaves',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
