# Generated by Django 2.2 on 2020-02-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200206_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='name',
            field=models.CharField(blank=True, default='Users Leaves', max_length=50),
        ),
    ]
