# Generated by Django 2.2 on 2020-02-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200207_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavebalance',
            old_name='LeaveBal_id',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='Allocated_Days',
            field=models.PositiveIntegerField(default=0, help_text='No of leave days allocated to a leave type per user per year'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='Available_Days',
            field=models.PositiveIntegerField(default=0, help_text='Remaining/available leave days per user'),
        ),
    ]
